name: 'Push Nupkg to GitHub Packages'
description: 'This cross-platform action publishes Nupkg to GitHub Packages.'
branding:
  icon: 'package'  
  color: 'green'
inputs:
  nupkg-path:  # id of input
    description: 'Path of NuPkg'
    required: true
  repo-owner:  # id of input
    description: 'package repository owner'
    required: true
  gh-user:  # id of input
    description: 'user account'
    required: true
  token:  # id of input
    description: 'access token'
    required: true
  skip-duplicate:  # id of input
    description: 'skip publishing duplicated package(s)'
    required: true
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'